services:
  mcp-docs:
    build:
      context: ../..
      dockerfile: docker/mcp-docs/Dockerfile
    image: mcp-docs:latest
    ports:
      - "8000:8000"
    env_file:
      - ../../.env
    restart: unless-stopped
