"""``dhcli self`` noun group: manage the dhcli tool itself.

Verbs: ``completion``.

The ``self`` noun names the dhcli installation as the operand (the
``rustup self`` / ``poetry self`` / ``uv self`` pattern), housing
verbs that operate on the tool rather than on Deephaven resources.
Today that is ``completion`` — print the shell tab-completion script
for one supported shell, so users enable completion with a single
line, e.g. ``eval "$(dhcli self completion zsh)"`` — and the group is
the intended home for future tool-self-management verbs (update,
diagnostics).

The completion scripts themselves are generated and maintained by
click (:mod:`click.shell_completion`); this module only selects the
right generator and prints its output as raw text. The supported set
is exactly click's native set: ``bash`` (>= 4.4), ``zsh``, and
``fish``.

The ``completion`` verb is declared ``needs_runtime=False``: it reads
no configuration and must work before any config tree exists (it is
typically run from shell startup files).
"""

from __future__ import annotations

__all__ = ["self_group"]

from typing import Literal, assert_never

import click
from click.shell_completion import (
    BashComplete,
    FishComplete,
    ShellComplete,
    ZshComplete,
)

from deephaven_mcp.cli._command import HelpfulCommand, HelpfulGroup
from deephaven_mcp.cli._errors import ExitCode
from deephaven_mcp.cli._help import (
    HelpEntry,
    HelpSpec,
    OutputSpec,
)

Shell = Literal["bash", "zsh", "fish"]
"""The shells with click-native completion support."""

SUPPORTED_SHELLS: tuple[Shell, ...] = ("bash", "zsh", "fish")
"""Accepted values for the SHELL argument, in documentation order."""

_OUTPUT = OutputSpec(
    "text",
    note=(
        "The completion script for SHELL, as plain shell source. Not "
        "subject to -o/--output: the script is the output."
    ),
)


@click.group("self", cls=HelpfulGroup)
def self_group() -> None:
    """Manage the dhcli tool itself.

    Verbs that operate on the dhcli installation rather than on
    Deephaven resources. The 'completion' verb prints the shell
    tab-completion script for bash, zsh, or fish; enable it with
    e.g. 'eval "$(dhcli self completion zsh)"'.
    """


@self_group.command(
    "completion",
    cls=HelpfulCommand,
    # Must work without a valid configuration tree — completion is
    # enabled from shell startup files, often before any config exists.
    needs_runtime=False,
    help_spec=HelpSpec(
        summary="Print the shell tab-completion script for SHELL.",
        description=(
            "Emits the tab-completion script for the given shell; "
            "evaluate it to enable completion for commands, "
            "subcommands, and options in the current shell, or add "
            "the line to your shell startup file to make it "
            "permanent. bash: add 'eval \"$(dhcli self completion "
            "bash)\"' to ~/.bashrc (requires bash >= 4.4). zsh: add "
            "'eval \"$(dhcli self completion zsh)\"' to ~/.zshrc. "
            "fish: add 'dhcli self completion fish | source' to "
            "~/.config/fish/completions/dhcli.fish. The script is "
            "generated by click and prints as raw text regardless of "
            "the -o/--output mode."
        ),
        arguments=(HelpEntry("SHELL", "Target shell: bash, zsh, or fish."),),
        output=_OUTPUT,
        examples=(
            '$ eval "$(dhcli self completion bash)"',
            '$ eval "$(dhcli self completion zsh)"',
            "$ dhcli self completion fish | source",
        ),
        environment=(),
        exit_codes=(ExitCode.SUCCESS, ExitCode.USER_ERROR),
        see_also=("dhcli --help", "dhcli agents tree"),
    ),
)
@click.argument("shell", type=click.Choice(SUPPORTED_SHELLS))
@click.pass_context
def completion(ctx: click.Context, shell: Shell) -> None:
    """Print click's completion script for ``shell`` as raw text.

    Args:
        ctx (click.Context): The click context; the root command and
            program name are resolved from it so the emitted script
            always matches the installed entry point.
        shell (Shell): The target shell, validated by ``click.Choice``.
    """
    match shell:
        case "bash":
            comp_cls: type[ShellComplete] = BashComplete
        case "zsh":
            comp_cls = ZshComplete
        case "fish":
            comp_cls = FishComplete
        case _:
            assert_never(shell)

    root = ctx.find_root()
    prog_name = root.info_name or "dhcli"
    complete_var = f"_{prog_name.replace('-', '_').upper()}_COMPLETE"
    script = comp_cls(root.command, {}, prog_name, complete_var).source()
    click.echo(script.rstrip("\n"))
