name: Build and Publish Wheels

on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    uses: ./.github/workflows/reusable-build-wheel.yml
    with:
      python-version: "3.11"
