name: Build Wheels

on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-wheels:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Upgrade pip and install build tools
        run: |
          python -m pip install --upgrade pip
          pip install build wheel
        working-directory: ./mcp-community

      - name: Build wheel
        run: |
          python -m build --wheel
        working-directory: ./mcp-community

      - name: Upload wheel artifact
        uses: actions/upload-artifact@v4
        with:
          name: wheel
          path: ./mcp-community/dist/*.whl

      # TODO: Uncomment and configure the following step to enable PyPI publishing
      #       Refer to the official documentation for detailed setup instructions: 
      #       https://github.com/pypa/gh-action-pypi-publish
      #       Ensure you have added your PyPI API token as a GitHub Secret named PYPI_API_TOKEN.
      #       The 'packages_dir' parameter specifies the directory containing the built wheel files.
      # - name: Publish to PyPI
      #   uses: pypa/gh-action-pypi-publish@release/v1
      #   with:
      #     user: __token__
      #     password: ${{ secrets.PYPI_API_TOKEN }}
      #     packages_dir: ./mcp-community/dist

