name: Coverage Report

on:
  workflow_run:
    workflows: ["Unit Tests"]
    types:
      - completed

jobs:
  coverage:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Download coverage artifact
        uses: actions/download-artifact@v4
        with:
          name: coverage-xml
          path: ./coverage

      - name: Display coverage report
        run: |
          cat ./coverage/coverage.xml

      # Add steps here to upload to Codecov, Coveralls, etc. if desired
      # - name: Upload to Codecov
      #   uses: codecov/codecov-action@v4
      #   with:
      #     files: ./coverage/coverage.xml
