name: Coverage Report

on:
  workflow_run:
    workflows: ["Unit Tests"]
    types:
      - completed

jobs:
  coverage:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Download all coverage artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: coverage-xml-*
          path: ./coverage

      - name: List downloaded files
        run: |
          find ./coverage

      - name: Display all coverage reports
        run: |
          for f in ./coverage/**/coverage.xml; do
            echo "--- $f ---"
            cat "$f"
          done

      # Add steps here to upload to Codecov, Coveralls, etc. if desired
      # - name: Upload to Codecov
      #   uses: codecov/codecov-action@v4
      #   with:
      #     files: ./coverage/coverage.xml
